### ISSUE TITLE
Documentation update, wiki

### ISSUE THREAD

**Issue by salvq** [Heckie75/voltcraft-sem-3600bt#2]
You may add to your wiki as an example of integration to Home Assistant for others.

Change XX to your device MAC address.

**Reading consumption, watts**

sensors.yaml
```
- platform: command_line
    name: voltcraft_watts
    json_attributes:
      - status
    command: "/home/homeassistant/.homeassistant/custom_components/voltcraft-sem-3600bt/vc-sem.exp XX:XX:XX:XX:XX:XX --status --json"
    unit_of_measurement: "W"
    value_template: >
      {{ value_json['status']['watts'] }}
```
**Script setup to turn the device off**

configuration.yaml
```
shell_command:
  script_voltcraft_turn_off: expect /home/homeassistant/.homeassistant/custom_components/voltcraft-sem-3600bt/vc-sem.exp XX:XX:XX:XX:XX:XX --off
```
scripts.yaml
```
  turn_off_action_voltcraft_script:
    alias: Voltcraft Turn OFF
    sequence:
        service: shell_command.script_voltcraft_turn_off
```
